config/routes.rb
Rails.application.routes.draw do
  resources :posts
  
  get "signup" => "users#new"
  get "login" => "sessions#new"
  delete "logout" => "sessions#destroy"
  resources :users 
  resources :comments
  
  resources :sessions, except:[:index, :edit, :update, :show, :new, :destroy]
  

   root "comments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    has_rich_text :content
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  has_rich_text :content
  
  belongs_to :user
  has_many :comments

end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    has_many :comments
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  helper_method :current_user

  helper_method :set_user 

  def set_user 
    if session[:user_id]
     @user =  User.find session[:user_id]
    end
  end
  

  def current_user

    if session[:user_id]
      User.find session[:user_id]
    end
  end

  def authenticate 
    if !current_user
      redirect_to signup_path, alert: "Invalid request"
    end
  end

  private
   
  def login(user)
      session[:user_id] = user.id
    end

    def logout
      session[:user_id] = nil
    end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


    def index
       
        @comment = Comment.all
    
    end

    def new

        @comment = Comment.new
    
    end

    def create
        @comment = current_user.comments.new(comment_params)
            respond_to do |format|
                if @comment.save
                    format.html { redirect_to root_path, notice: "Comment was successfully created. "}
                    format.json { render :show, status: :created, location: @comment }
                else
                    format.html { render :new, status: :unprocessable_entity }
                    format.json { render @comment.errors, status: :unprocessable_entity }
                end
            end
     end

    def show
        @comment = Comment.find(params[:id])
    end

    def edit
        @comment = Comment.find(params[:id])
      end 

    def update

    end

    def destroy

    end

    private 



    def comment_params
        
        params.require(:comment).permit(:title, :content)
    
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    before_action :authenticate
   


    def index

    end

    def show 
        
    end

    def update

    end

    def create

    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_user

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    
    end
  
    def create
    
        @user = User.where(email: params[:email]).first
    
      if @user && @user.authenticate(params[:password])
        login(@user)
        redirect_to root_path, notice: "Log In Successful"
      else
        redirect_to login_path, alert: "Invalid Email or Password"
      end
    
    end 
  
    def destroy 
      
      session.delete(:user_id)
      redirect_to root_path, alert: "You have Logged Out."
    
    end
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate, except: [:new, :create]
  
    def new
      @user = User.new
    end
  
    def create 
      @user = User.new user_params
      if @user.save
        login(@user)
        redirect_to root_path, notice: "You have successfully signed up."
      else
        render :new, status: :unprocessable_entity
      end
     end

    def show 
      @user = current_user
    end
  
     private
  
     def user_params
      params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation, :email)
     end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user

        if session[:user_id]
          User.find session[:user_id]
        end
      end
      
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_form.html.erb
<%= form_with model: @comment do |form| %>
  <div class="trix-content">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group my-3">
    <%= form.submit "Submit", class: 'form-control' %>
  </div>
<% end %>

app/views/comments/index.html.erb
<% @comment.each do |comment| %>
    
    <%= comment.title %>
    <%= comment.content %> 

<% end %>

app/views/comments/new.html.erb
<%= render "form" %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Work Station</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <% if current_user %>
      <!-- current_user will return true if a user is logged in -->
       <%# <%= "Logged in as #{current_user.email}"  %> 
      <%= link_to 'Log Out', logout_path, data: { turbo_method: :delete }, class:"nav-link"%>
    </li>
    <% else %>
      <!-- not logged in -->
      <li>
    <%= link_to 'Log In', login_path, class:"nav-link"%> 
      </li>
      <li>
    <%= link_to 'Sign Up', signup_path, class:"nav-link" %>
    <% end %>
    
      </li>
         <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
 
    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Comment:</strong>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/users/new.html.erb
<div class="container  text-center mt-5">
<h1 class="text-medium"><u>Sign Up</u></h1>
  <%= form_with model: @user do |form| %>
  <div class="card">
    <div class="card-body ">
      <div class="mb-3">
        <%= form.label :first_name  %><br>
        <%= form.text_field :first_name %>
        <% @user.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
        <% end %>
      </div>
      <div class="mb-3">
        <%= form.label :last_name %><br>
        <%= form.text_field :last_name, :class => 'text-medium'%>
        <% @user.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
        <% end %>
      </div>
      <div class="mb-3">
        <%= form.label :email %><br>
        <%= form.text_field :email, :class => 'text-medium' %><br>
        <% @user.errors.full_messages_for(:email).each do |message| %>
        <div><%= message %></div>
        <% end %>
      </div>
      <div class="mb-3">
        <%= form.label :password_confirmation %><br>
        <%= form.text_field :password_confirmation, :class => 'text-medium' %><br>
        <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
        <div><%= message %></div>
        <% end %>
      </div>
      <div class="mb-3">
        <%= form.label :password %><br>
        <%= form.text_field :password, :class => 'text-medium' %><br>
        <% @user.errors.full_messages_for(:password).each do |message| %>
        <div><%= message %></div>
        <% end %>
      </div>
      </div>
      <%= form.submit %>
      </div>
   </div>
  <% end %>
</div>